name: Mobile app tests
on: 
  pull_request:
      branches:
        - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up node js
        uses: actions/setup-node@v1
        with:
          node-version: 14.15
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: mobileapp/node_modules
          key: ${{ runner.os }}-${{ hashFiles('mobileapp/package-lock.json') }}
      - name: Install npm dependencies
        run: npm install
        working-directory: mobileapp
      - name: Run tests
        run: npm test
        working-directory: mobileapp
