name: Prettier

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        prettier_options: --write **/*.{js,jsx,css,json,ts,tsx}
        commit_message: Code prettified
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
